export default [
  "There is always some madness in love. But there is also always some reason in madness.",
  "Always forgive your enemies; nothing annoys….",
  "The best way to predict the future is to create it.",
  "Have no fear of perfection - you’ll never reach it.",
  "Your thoughts become things...",
  "You will face many defeats in life, but never let yourself be defeated.",
  "Two heads, one heart.",
  "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO",
  "The most difficult thing for me is a portrait. You have to try and put your camera between the skin of a person and his shirt.",
  "Be yourself; everyone else is already taken.",
  "Let come what comes, let go what goes. See what remains.",
  "Don’t tell me the sky is the limit when there are footprints on the Moon.",
  "Sisters function as safety nets in a chaotic world simply by being there for each other.",
  "I think, therefore I am.",
  "Simplicity speaks a thousand words.",
  "Quality is not an act, it is a habit.",
  "To live is to suffer; to survive is to find some meaning in the suffering.",
  "There is a pleasure in the pathless woods...",
  "The journey of a thousand miles begins with one step.",
  "The true work of art is but a shadow of the divine perfection.",
  "You could not step twice into the same river.",
  "I had been trained like that.",
  "To live is to suffer, to survive is to find some meaning in the suffering.…",
  "Chaos is a friend of mine…",
  "Quality is not an act, it is a habit.",
  "It does not matter how slowly you go as long as you do not stop...",
  "How big would you dream if you knew you couldn’t fail...",
  "It doesn’t matter who we are,that matters is our plan",
  "Have dreams otherwise you are not living..You just surviving",
  "Photography is about capturing souls, not smiles.",
  "Time spent among trees is never wasted.",
  "The best view comes after the hardest climb.",
  "It's strange that they fear death. Life hurts a lot more than death.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Pleasure in the job puts perfection in the work.",
  "Nobody owns life, but anyone who can pick up a knife owns death…",
  "The greater the difficulty, the more glory in surmounting it",
  "No man's knowledge here can go beyond his experience",
  "Happiness is not something ready-made. It comes from your own actions.",
  "Beauty is everywhere, you just have to see it first.",
  "The mind is furnished with ideas by experience alone",
  "Knowing yourself is the beginning of all wisdom",
  "A dream doesn't become reality through magic; it takes sweat, determination and hard work.",
  "Hope. It is the quintessential human delusion, simultaneously the source of your greatest strength and your greatest weakness.",
  "The mind once enlightened cannot again become dark",
  "Great photography is about depth of feeling, not depth of field.",
  "Everyone has a chapter they don’t read out loud",
  "Character, like a photograph, develops in darkness.",
  "If slavery is not wrong, nothing is wrong.",
  "Life is full of ups and downs. Walk on the right path",
  "Life is the biggest party you'll ever be at.",
  "Discipline is the bridge between goals and accomplishment",
  "Music is life. That’s why our hearts have beats",
  "Just because you're awake doesn't mean you should stop dreaming",
  "Grandmas hold our tiny hands for just a little while…..but our hearts forever",
];
